### ISSUE TITLE
Protectorat

### ISSUE THREAD

**Issue by Inccubus** [pumpi/troop-creator#1]
Der Avatar of Menoth gehört nicht zur Kampfgruppe des Casters.
Deshalb gelten die Punkte die der Caster für Jacks freischaltet nicht für den Avatar.
Mann zahlt immer die vollen 11 Punkte für ihn.

Bei den Castern fehlt dir "Vizescrutator Vindicus"
Er schlatet 6 Punkte für Jacks frei.

MFG Roman

**Comment by pumpi** [comment]
Vielen dank das werde ich gleich mal mit aufnehmen

**Comment by pumpi** [comment]
Fehler behoben
7dcc4ca55e5e9775db6a5e6d54f607e879a386d9

**Comment by pumpi** [comment]
Avatar ist nun ein Solo Warjack wie gewünscht 7dcc4ca55e5e9775db6a5e6d54f607e879a386d9
"Vizescrutator Vindicus" wurde hinzugefügt 9453e10a07e0b51709d43bd40361c1c47e139755

**Comment by Inccubus** [comment]
Sorry nächtes Problemm mit dem Avatar
Wenn ich eine Arme mit z.B. 15 Punkten spielen will und zuerst den Caster, dann den Avatar wähle
kann ich keinen Jack wählen der teurer ist als 4 Punkte.
Was ja passen würde wenn ich vorcher schon andere Jack´s gewählt hätte, welche die freien Punkte, die der Caster mitbringt, ausgenutzt haben.
Wenn ich mir zuerst einen/mehrere Jacks aussuche und danach den Avatar ist es kein Probelmm

**Comment by Inccubus** [comment]
Bei den Solos fehlt dir der "Attendant Priest"
Punkte: 2                    Feldmax.: 2

Wegen ihm müsstest du noch eine Kategorie in der Protectoratlist einfügen.
Er hat nämlich die Regel, dass er sich Söldner mit kleiner oder mittlerer Base anschliest und diese dann als verbündete Fraktionsmitglieder gelten.
Also als Truppen des Protectorats.
