### ISSUE TITLE
Lynus & Edrea bei Cygnar

### ISSUE THREAD

**Issue by SirMythos** [pumpi/troop-creator#109]
Lynus Wesselbaum & Edrea Lloryrr spielen auch bei Cygnar. 
Aktuell kann ich diese nicht auswählen.

**Comment by Hjard** [comment]
Sind definitiv verfügbar, bitte einmal Cache leeren, das System muss erstmal drauf kommen jetzt auch Minions bei Cygnar zu laden usw.
