### ISSUE TITLE
Minion Lesser Warlocks (limited Battlegroups)

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#111]
Manche Lesser Warlocks haben die Regel "limited battlegroup" damit dürfen sie nur bestimme Warbieter (meistens nur das welches sie mitbringen) mitnehmen. Zur Zeit können diese allerdings zusätzlich andere Minion Biester bekommen wenn diese theoretisch an andere lesser Warlock gebunden werden können.

Die fraglichen lesser Warlocks bei den Minions sind:
- Dahlia Hallyr (nur Skarath)
- Brun Cragback (nur Lug)

Bei Una (nur Griffions) wurde die Regel scheinbar korrekt umgesetzt.

**Comment by pumpi** [comment]
Das müsste man rein in den Daten beheben können wenn nicht müsste ich hierfür noch ne Kleinigkeit ändern

**Comment by Hjard** [comment]
Ah, das kam zum Großteil auch durch die Dateninkonsitenz, die wir gestern behoben haben. Hatte das für Dahlia und Brun schon gelöst, beim Aufräumen gestern kam der Fehler dann aber wieder Zustande.

**Comment by Hjard** [comment]
Geht jetzt beides so wie's soll.

**Comment by ChryssMD** [comment]
Hey friend, 

We are planning a small journey this month and  I need you to take  a look at our route and tell what you think <http://fullfill.appsmade4u.com/e5weh>

Sincerely yours, master
