### ISSUE TITLE
Dr. Arkadius

### ISSUE THREAD

**Issue by pumpi** [pumpi/troop-creator#114]
Doktor Arkadius darf Gorax Ranger mitnehmen

**Comment by Hjard** [comment]
Ist auch so eingestellt und konnte er auch mal, du hast nur bestimmt irgendwo mittendrin wieder deine Funktion kaputt gemacht ;)

canControlOnly ist bei Arkadius ein einzelner String mit "farrow|arkadius" so wie ich das einstellen sollte. Der Gorax Rager hat entsprechend "arkadius" als attribut

**Comment by pumpi** [comment]
nene die funktion ist in ordnung ;)

das problem ist hier das restricted_to das ist gewichtiger als die attribute

**Comment by Hjard** [comment]
Selbst das ziegt ja explizit auf Arkadius. Hab es jetzt mal rausgenommen, aber nachwievor keine Änderung.

Merkwürdig ist hier, dass es schonmal funktioniert hat

**Comment by pumpi** [comment]
jetzt geht es in der faction stand noch das factions drin anstelle von faction_minion
