### ISSUE TITLE
Link Generierung falsch

### ISSUE THREAD

**Issue by Hjard** [pumpi/troop-creator#116]
Klicke mir vorhin eine Liste mit Lilith3 zusammen, schick den Link Freunden und die Wundern sich, warum ich denn Kryssa in meiner Lilith3 Liste als Caster drin hab. Stellt sich heraus: Beim Link generieren macht er irgendwie aus Lilith3 Kryssa.

Ich hab die dumpfe Vermutung, dass das nicht nur da passieren wird.

**Comment by pumpi** [comment]
hast du mir den link

**Comment by Hjard** [comment]
So siehts aus
![image](https://cloud.githubusercontent.com/assets/19911689/16521003/3c966426-3f94-11e6-8f2e-ef7aa0a6a22e.png)

Kopier ich den [Link](http://troop-creator.net/#/build/everblight?sel=RVcxNEBtazM%3D&caster=1&points=75&tier=&objective=) dann oben raus und rufe ihn wieder auf steht da plötzlich Kryssa

**Comment by pumpi** [comment]
Kryssa und Lylyth3 haben die selbe ID

**Comment by Hjard** [comment]
Wer das wohl wieder verbockt hat? xD

Hah! Mir fällt ein, ich war's tatsächlich nicht! Als ich Kryssa hinzugefügt hab, hatten alle noch die alten IDs

**Comment by pumpi** [comment]
habs geändert sollte nun gehen
