### ISSUE TITLE
Morrowan - Tarmarite animosity not working correctly

### ISSUE THREAD

**Issue by Grauenacht** [pumpi/troop-creator#123]
I don't think that Precursor Knights have the label Morrowan on them, because I can use them with Acosta or Alexia.
Constance Blaize has the same thing, I think if you add a label like Harlan Versh or Gallant, it shouls work correctly.
Many thanks for making this great tool.

Grauenacht

**Comment by pumpi** [comment]
http://privateerpress.com/warmachine/gallery/cygnar/units/precursor-knights

Classification:  Morrowan Ally Unit

You right i correct it ;)

**Comment by pumpi** [comment]
the animosities was not load i fix it thx for the report
