### ISSUE TITLE
Add new Warcaster (Ex-Journeyman) aus den Gen Con Spoilern

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#124]
Ich muss dringend mal ne Allie2 Liste schreiben :)

Achtet dann auch gleichdarauf das ich Allie1 (Solo Journeyman) nicht mitnehmen darf. (Analog können die anderen Fraktionen auch eingefügt werden, muss aber nicht.)

**Comment by Plastefuchs** [comment]
Tsk Tsk Tsk. ;)
Die 5 Juniors sind doch schon drinn, die Einschränkung bzgl der Juniors kommt nocht.
