### ISSUE TITLE
[Scyrah] Fehlende Auswahl (Soulless Escort)

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#13]
Issue: Das Modell Soulless Escort fehlt in der Scyrah Liste, dies ist ein generisches Weapon Attachment das zu vielen Scyrah Auswahl angefügt werden kann.

Fix: Modell hinzufügen, Zuläsige Zuordnungen beachten.

Tags: fehlendes Modell, Scyrah

**Comment by ChryssMD** [comment]
Kümmer ich mich drum. Dazu nur eine Frage: Wie wurden denn eigentlich die IDs festgelegt? Wirkt im Code etwas willkürlich aber ich hab wenig Lust mir eine aus den Fingern zu sauegn und alle zu überprüfen.

**Comment by pumpi** [comment]
ja die habe ich leider von den vorherigen Daten übernommen. Ändern würde ich daran aber erstmal auch nichts. bis jetzt habe ich immer geschaut welches die höchste Zahl ist und habe dann einfach +1 gemacht also nicht verkopfen und die bestehenden weiterführen. Für die ZUkunft könnte man sich da irgendeine vereinheitlichung überlegen

**Comment by ChryssMD** [comment]
Klingt erstmal okay, dann füg ich das ein. Ich hab Zugang zu allen Daten und Tierlisten, brauchst dir also nix mehr aus dem Battle College raussuchen... :)

**Comment by pumpi** [comment]
Das stimmt nicht das Modell gibt es es ist nur unter Solos wird aber richtigerweise erst freigegeben wenn eine Unit ausgewählt wird also sollte es eher ein UA sein denke ich
