### ISSUE TITLE
Ranking Officer kann ohne Söldnereinheit eingefügt werden.

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#14]
Issue: Ranking Officers sind UAs die nur an Merc-Einheiten angefügt werden können und hier auch den UA Slot belegen. Zur Zeit werden diese als Solos eingefügt. Beispiel: Jonas Murdoch (Cygnar)

Fix: Ranking Officer Regel implementieren, UA Slot Belegung beachten.

Tags: Mechanik, Cygnar, Ranking Officer, UA

**Comment by ChryssMD** [comment]
Der nimmt ja eh den UA Slot ein, da könnte man den auch genauso implementieren. Ich denke ich komme heute Abend dazu mir das mal anzugucken.

**Comment by pumpi** [comment]
kann der auch als reines Solo gespielt werden? gibt es eigentlich Möglichkeiten das mehrere UAs an einer Einheit sind? wenn nicht muss ich die Überprüfung noch einbauen ;)

**Comment by ChryssMD** [comment]
Nein, kann er nicht. Er besetzt den UA Slot einer Einheit. Diese kann dann auch kein weiteres UA bekommen. Würde Sea Dogs und Highshield betreffen. Also könnte man den einfach als UA mit restriktion auf die Merc-Einheiten einbauen. Wäre von daher eher ein Datenfehler, das kann ich später einfach korrigieren.

**Comment by ChryssMD** [comment]
Generelle gilt: Eine Einheit kann nur ein UA und eine WA-Auswahl (bis zu deren FA) mitnehmen.
