### ISSUE TITLE
[Cygnar] Nemo3 kann fehlerhaft einen Squire erhalten.

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#15]
Issue: Da Nemo3 schon ein Attachment mitbringt, sollte er keinen Squire erhalten dürfen. Ausserdem wird der Squire wie ein normales Solo behandelt.

Fix: Attachment Regel implementieren, Nemo3 (und ggf. andere) entsprechend markieren.

Tags: Mechanik, Cygnar, Attachment

**Comment by ChryssMD** [comment]
Das betrifft natürlich zur Zeit alle Warcaster die ein Attachment mitbringen und eine Attachment Auswahl in ihrer Faction haben.

**Comment by pumpi** [comment]
ich glaube für sowas müssen wir ein weiteres Attribut in die Daten packen wie alsoAdd oder sowas weil die Begleiter kommen ja automatisch mit

**Comment by ChryssMD** [comment]
Vermutlich, die Caster Attachments sind ja schon als entsprechender Typ markiert.

**Comment by Cannonbal** [comment]
Ich weiß grad nicht ob ich dafür ein extra Issue eröffnen soll, aber ohne die angesprochene Attachment Regel ist es quasi jedem Caster möglich 2 Warcaster Attachments aufzunehmen. 

Getestet mit Brisbane (Squire + Sylys Wyshnalyyr) und bei Khador mit Butcher und Old Witch. Hier dann halt mit War Dog + Sylys.
Wenn die Warcaster Attachment Regel implementiert ist, sollte das Problem schon behoben sein. Es muss dabei aber der Sonderfall Butcher3 Tierliste beachtet werden, damit man in diesem Fall "n" zusätzliche War Dogs hinzufügen kann.

**Comment by ChryssMD** [comment]
Tierlisten haben eh Ausnahmeregeln in Kraft mit denen das möglich ist. Ich vermute (hab mir diesen Code noch nicht angeguckt) das man das Attachment hinzufügen ähnlich macht wie die UAs (die Pikemen sollten da mit zwei verschiedenen UAs das Beispiel der Wahl sein).
