### ISSUE TITLE
[Tierliste: Darius NQ]

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#17]
Issue: In der NQ Tierliste von Darius wird für jeden Stormwall ein Stormcaller umsonst und ohne FA hinzugefügt. Zur Zeit ist dies jedoch nur für den ersten Stormwall der Fall.

Fix: Bonus korriegieren, FA Berechnung von Tierliste und Modellen abhängig machen.

Tags: Mechanik, Tierliste, Cygnar

**Comment by ChryssMD** [comment]
Ich hab dazu gerade mal in die Datenbasis geguckt, offenbar müsste man hierzu eine Änderung der Tierlisten-Engine einbauen. Eine "For each" Funktion ist offenbar nicht vorgesehen.

**Comment by pumpi** [comment]
Ich kümmer mich darum. Leider habe ich die Datenbank so übernommen aber ich denke der hat sich da schon was dabei gedacht und wenn das überall so ist kann ich da durchaus eine Funktion drum herum bauen

**Comment by ChryssMD** [comment]
Ich hab die Foreach Sache gefunden, hab deshalb den Kommentar gelöscht, ich bin gerade dabei das einzubauen. :)
