### ISSUE TITLE
[Circle Orboros] Bradigus Tier 4

### ISSUE THREAD

**Issue by pumpi** [pumpi/troop-creator#30]
Hier wird das Tier 4 falsch berechnet da bisher auf ein Tier Bonus in dem Modelle nicht vorkommen beachtet wurde.

**Comment by ChryssMD** [comment]
Wie gesagt, glaube ich das man das evtl über die "erlaubte Modelle" Liste in der T4 Stufe machen könnte...

**Comment by pumpi** [comment]
ja kann man auch aber ist so noch nicht implementiert muss ich noch machen
