### ISSUE TITLE
Animositäten berücksichtigen

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#31]
Issue: Bestimmte Modelle (in der Regel Morrowaner aber auch Victor Pendrake) haben eine Animosität zu anderen Modell/Typen.

Fix: Datenbestand ändern oder Regel Animosität implementieren.

**Comment by Hjard** [comment]
Daten sind soweit ergänzt, fehlt noch die Logik dahinter

Die Lösung wird auch die #75 beheben
