### ISSUE TITLE
[Tierliste: Lucant] UA ändert die Einheit auf "mit Fernkampfwaffen" für T2 und T3

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#36]
Für T2 reicht es wohl die UA Id in die Tierbedingung aufzunehmen. Bei T3 wird das vermutlich kniffliger.

**Comment by pumpi** [comment]
T3 wird richtig kacke wenn das UA den Status ändert das kann ich so nicht überprüfen

**Comment by ChryssMD** [comment]
Ja, hab ich auch im Code gesehen das das schwierig wird. eventuell müsste man da neue relationen ähnlich wie "forEach" (also eher "without" oder so) in den bestand einbauen.

Da sollten wir aber lieber mal etwas länger drüber nachdenken, immerhin sollte der Code ja nicht so voller Ausnahemen werden. Eventuell findet man was das mehrerer Probleme lösen kann.

**Comment by ChryssMD** [comment]
Hmm, durch eine "not" relation in den Bedingungen könnte man übrigens auch das Bradigus Problem lösen.
