### ISSUE TITLE
[Tierliste: Arkadius NQ] Splatter und Battle Boar hinzufügen

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#37]
Aber: für diese Beasts gibt es kein gratis Razor Boa (Aussage Kalfan).

Mit Warroom prüfen und einbauen.

**Comment by pumpi** [comment]
Laut NQ56 ist das so allerdings ist der Datenbestand bereits richtig eventuell wurde das mal mit einem anderen Fehler behoben
