### ISSUE TITLE
Weapon Attachments werden nicht korrekt angefügt

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#4]
Issue: Beim Hinzufügen von Weapon Attachments wird nur jeweils die erste Auswahl an eine Einheit angegliedert. Da in den meisten Fällen bis zu 3 WAs an eine Einheit angefügt werden können ist dies ein Fehlerhaftes Verhalten.

Fix: Entweder die Möglichkeit einbauen WAs in den Punktekosten zu erhöhen (wie bei den Einheitsgrößen) oder eine 1:N Beziehung aufbauen so das mehrere Auswahlen angefügt werden können.

Tags: Mechanik, Weapon Attachments

**Comment by pumpi** [comment]
Wurde mit dem letzten update eingefügt
