### ISSUE TITLE
[Tierliste Morghoul2 - Imperial Executioners] darf nicht enthalten abfrage

### ISSUE THREAD

**Issue by pumpi** [pumpi/troop-creator#41]
Speziell hierfür brauchen wir eine nicht enthalten Bedingung bei den Tier listen Konfiguration diese kann auch hilfreich bei anderen listen sein

**Comment by ChryssMD** [comment]
Greetings! 


I guess  I've just  found something  perfect for  you, you're gonna  admire that!  Just take a look  here <http://agree.918forlease.com/e5qbeu>

master
