### ISSUE TITLE
Jack Marshal funktioniert noch nicht

### ISSUE THREAD

**Issue by SirMythos** [pumpi/troop-creator#45]
Das hinzufügen oder umhängen von Jacks an einen Jack Marshal funktioniert noch nicht (am Beispiel ATGM-Officer getestet). 

Wenn ich einen Jack hinzufüge, wird dieser immer an den Caster gehängt.
Wenn ich nur Jack Marshals in der Liste habe, darf ich keine Jacks hinzufügen.

**Comment by pumpi** [comment]
haben wir schon aufgenommen in #5 

wird in nächster zeit umgesetzt
