### ISSUE TITLE
Anpassen der Default-Punktzahl

### ISSUE THREAD

**Issue by derCeleb** [pumpi/troop-creator#49]
Die Default-Punktzahl sollte von 25 auf 50 geändert werden, da dies die wohl meistgespielte Punktgröße ist.

**Comment by pumpi** [comment]
Die Diskussion habe ich auch schon stark im Page5 Forum geführt ich werde hier eine andere Lösung anstreben. Es wird hier eine Buttonleiste geben mit der man einfach mit einem klick die vorgegebene Größen aus den Regelwerk starten kann. 50 hier zum Standard zu nehmen wird dann vermutlich so sein.

**Comment by pumpi** [comment]
Wurde angepasst und nun gibt es einen zusätzlichen Select für Casterzahl und Punktezahl
