### ISSUE TITLE
Untergeordnete Auswahlen können nicht verschoben werden.

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#5]
Issue: Sowohl UAs als auch WAs und Warjacks können nicht innerhalb der Liste verschoben werden.  Dies betrifft sowohl Jackmarshals als auch Journeymen mit Kampfgruppenregel.

Fix: Entweder Dialogbox zur Auswahl einfügen oder (bevorzugt) eine Drag& Drop Lösung einbauen.

Tags: Mechanik, GUI

**Comment by ChryssMD** [comment]
Ich gebe zu das Drg&Drop ist ein Enhancement, aber wir brauchen eine Lösung für das Marshall/Journeyman Problem. Ohne das kann zumindest Cygnar überhaupt keine richtigen Turnierlisten schreiben.

**Comment by pumpi** [comment]
Ja das mir schon klar aber da das noch nicht vorhanden ist ist es eine erweiterung. das ist aber die nächste ToDo auf meiner liste also keine Sorge kriege ich hin. Ob ich das mit Drag & drop mache weis ich noch nicht da die datenstruktur der auswahl liste eindimensional ist weil sie ja in die URL muss aber ich lass mir da was einfallen.

**Comment by SirMythos** [comment]
Ah, hatte ich übersehen, sonst hätte ich den Issue nicht aufgemacht.
Übrigens gefällt mir das Projekt echt gut.

**Comment by pumpi** [comment]
Ja kein Problem erwarte ich auch nicht das jeder sich alle durchliest ich makier das halt dann als duplicated und schließe es ;)
Danke freut mich zu hören hoffe ich werde da noch lange viel spaß mit haben und schöne sachen mit entwickeln :)

**Comment by pumpi** [comment]
the drag and drop remove while its not mobile i must search an other one
