### ISSUE TITLE
[Tierliste] eCaine NQ34 erhöht max_attache für WAs nicht

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#6]
Issue: Wenn die gleiche Einheit mehrfach eingefügt wird, können fehlerhafterweise nicht allen Auswahl Weapon Attachments angefügt werden. Die Gesamtzahl wird vermutlich nicht per Einheit erhöht.

Fix: Berechung der FA an die Einheitenanzahl koppeln

Tags: Mechanik, WAs

**Comment by ChryssMD** [comment]
Meinst du das das ein Fehler in den Datenstrukturen ist? Kann man das FA auch als ForEach angeben? und die Frage ist wie man die Zuordnung macht, damit nicht eine Einheit 4 WAs bekommt. Ich guck mal rein, kann ich aber vermutlich heute noch nicht klären.

**Comment by pumpi** [comment]
Es gibt irgendwo ein beispiel für das forEach ich suche es raus und geb dir bescheid ich habe das auf jeden fall implementiert

**Comment by ChryssMD** [comment]
Wenn es das gibt, finde ich das auch :)

**Comment by pumpi** [comment]
epic Grim - Hunting Party Tier Level 1

**Comment by pumpi** [comment]
Bei welcher Tier liste war das? Ich habe einen Fehler behoben weis aber nicht ob dieser hier damit auch behoben wurde.
