### ISSUE TITLE
Tierliste Mortenebra Tier 3 Voraussetzungen fehlerhaft

### ISSUE THREAD

**Issue by VivaAndromeda** [pumpi/troop-creator#60]
In der Mortenebra Tierliste stimmen die Tier 3 Voraussetzungen nicht. Somit ist es möglich Einheiten mitzunehmen und trotzdem Helljacks günstiger zu erhalten.

**Comment by pumpi** [comment]
OK der Fehler ist hier das mein Tier Checker das darf nicht enthalten noch nicht kann habe ich bereits aufgenommen und wird auf jeden fall demnächst eingefügt
Duplicate of #41
