### ISSUE TITLE
Cygnar: Stormblade Infantry Weapon Attachment

### ISSUE THREAD

**Issue by robmweb** [pumpi/troop-creator#63]
Cygnar Stormblade infantry can have up to 3 of their Weapon Attachments, the tool only allows 1 or 2

**Comment by pumpi** [comment]
i have read in the book an there are write this
Up to 2 Add’l Gunners 1EA

did this mean 1 and 2 Add'l?

**Comment by robmweb** [comment]
On the card it is written under point cost:
1 Storm Gunner                      1
Up to 2 additional Gunners     1ea

So you can take 3 as a weapon attachment for a unit.

**Comment by pumpi** [comment]
ok my fault i correct it
