### ISSUE TITLE
Attachement Solo

### ISSUE THREAD

**Issue by pumpi** [pumpi/troop-creator#69]
Es gibt Solos die nur den Castern angegliedert werden können diese haben auch schon den richtigen Typ allerdings beachtet der TroopCreator die noch nicht und fügt das Solo nicht dem Caster hinzu

**Comment by chrisdopuch** [comment]
+1

Another thing to note is that the warcaster attachment should be mutually exclusive with other warcaster attachments
e.g. warcaster can either Sylys Wyshnalyrr _or_ the Khador wardog attachment, but not both

**Comment by pumpi** [comment]
i actualy work on it the thing what you say that only can add one attachement is the last step before release ;)
