### ISSUE TITLE
Khador MOW Drakhun mount/dismount

### ISSUE THREAD

**Issue by MMansoNN** [pumpi/troop-creator#71]
It seems that there is no option for the Khador man-o-war drakhun to switch between with/without dismount (4/5 points)

**Comment by pumpi** [comment]
Yes Dismount is at the moment not implemented but i put this issue to the enhachments

**Comment by chrisdopuch** [comment]
+1 I would like to see this

I might look into implementing this if I have the time

**Comment by pumpi** [comment]
Thx for your help chris. If you have any questions for implementing ask me ;)
