### ISSUE TITLE
no deleting complete list by changing tier

### ISSUE THREAD

**Issue by pumpi** [pumpi/troop-creator#78]
at the moment we delete the complete list at changing tier but we only must delete not allowed models.

**Comment by Hjard** [comment]
Not an issue anymore. New theme forces do not have tiers and will HAVE to be reset every time you change to another one, since allowed models will probably change drastically from theme force to theme force / regular list.

**Comment by pumpi** [comment]
but the problem in the future is we can play same caster in other list then we dont like klick the caster in again and again ;)
