### ISSUE TITLE
Bug report on Maelok's Battlegroup

### ISSUE THREAD

**Issue by Lengytam** [pumpi/troop-creator#79]
Hi!

I've tried your troop creator site, and saw that if I choose Maelok as my warlock, I can  include only Farrow beasts in his battlegroup, although he's a Gatorman.
Also there are no available beasts for Barnabas, Rask is missing from the list of warlocks, and some mercenary units (or cygnaran units allowed for mercenaries) still have their mk2 point cost:
-Nyss Hunters (as minions)
-Dannon Blythe & Bull (as minions)
-Boomhowler & Co. (as minions)
-ATGM
-Long Gunner Infantry
-Rangers
-Sword Knights
-Trencher Commandos
-Trencher Infantry
-Lynus & Edrea (as mercenaries)

Btw thanks for the site, it's really neat, and easy to use.

Regards,
T.L.

**Comment by pumpi** [comment]
at the moment we have problems with mercs and minions while loosing his contracts. We working on it

**Comment by Hjard** [comment]
Minion Warlocks are working again. 
I'm checking the rest of the data errors atm
