### ISSUE TITLE
Zusätzliche Auswahlen werden nicht beachtet

### ISSUE THREAD

**Issue by ChryssMD** [pumpi/troop-creator#9]
Issue: Sobald Gaston Crosse in der Liste ist, sollten es möglich sein ihm Söldnerwarjacks anzuhängen. Diese werden jedoch nicht als legale Auswahl erkannt.

Fix: Die Regel Mercenary Journeyman sollte implementiert werden. Dieses Problem hängt auch vermutlich mit dem fehlerhaften Verschieben von Warjacks zusammen.

Tags: Mechanik, Journeymen, Söldner

**Comment by pumpi** [comment]
Diese Funktionalität wurde hinzugefügt
