### ISSUE TITLE
Removing BG Models - Smartphone

### ISSUE THREAD

**Issue by Hjard** [pumpi/troop-creator#98]
Removal of Battlegroup models on touch devices is difficult. Most of the time the drag function activates instead of removing the model.

Observed on android 4.4 , chrome

Recommendet solution: Require a longer hold to activate the drag.

**Comment by pumpi** [comment]
there is an option in jQueryUI draggable to do that i whil change this

http://api.jqueryui.com/draggable/#option-delay
